sudo: required
dist: trusty
language: python
python: 3.6
addons:
  apt:
    packages:
    - python3-pip
    - libsdl1.2-dev
    - libsdl2-dev
    - libfreetype6-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libpng-dev
    - pkg-config
    - zlib1g-dev
    - liblircclient-dev
    - binutils-dev
    - nasm
    - libopencv-dev

env:
 - CC=gcc MESON_CONFIGURE="-Dosd=true"
 - CC=gcc MESON_CONFIGURE="-Dosd=false"
 - CC=gcc MESON_CONFIGURE="-Dno_asm=true"
 - CC=gcc MESON_CONFIGURE="-Dlirc=true"
 - CC=gcc MESON_CONFIGURE="-Ddebugger=true"
 - CC=gcc MESON_CONFIGURE="-Ddbg_compare=true"
 - CC=gcc MESON_CONFIGURE="-Ddbg_core=true"
 - CC=gcc MESON_CONFIGURE="-Ddbg_count=true"
 - CC=gcc MESON_CONFIGURE="-Ddbg_profile=true"
 - CC=gcc MESON_CONFIGURE="-Ddbg_timing=true"
 - CC=clang MESON_CONFIGURE="-Dosd=true"
 - CC=clang MESON_CONFIGURE="-Dosd=false"
 - CC=clang MESON_CONFIGURE="-Dno_asm=true"
 - CC=clang MESON_CONFIGURE="-Dlirc=true"
 - CC=clang MESON_CONFIGURE="-Ddebugger=true"
 - CC=clang MESON_CONFIGURE="-Ddbg_compare=true"
 - CC=clang MESON_CONFIGURE="-Ddbg_core=true"
 - CC=clang MESON_CONFIGURE="-Ddbg_count=true"
 - CC=clang MESON_CONFIGURE="-Ddbg_profile=true"
 - CC=clang MESON_CONFIGURE="-Ddbg_timing=true"

install:
  - python3 --version
  - export PATH="`pwd`/build:${PATH}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build; fi
  - pip3 install meson

script:
  # XXX: disable LTO for now to avoid clang link failure
  - meson -Db_lto=false "$MESON_CONFIGURE" builddir
  # disable LTO when using clang, because broken Travis packages can't find LLVMgold.so plugin at linkk time...
  #- if [[ "${CC%%+*}" == "clang" ]]; then meson configure -Db_lto=false builddir; fi
  # Print configuration just to make sure we got it right
  - meson configure builddir
  - ninja -C builddir

# extra mxe build entries
matrix:
  include:
    - env:
      - MXE_CPU=i686
      - PATH="/usr/lib/mxe/usr/bin/:$PATH"
      addons:
        apt:
          sources:
          - sourceline: 'deb http://pkg.mxe.cc/repos/apt/debian jessie main'
            key_url: 'http://pkg.mxe.cc/repos/apt/conf/mxeapt.gpg'
          packages:
          - mxe-i686-w64-mingw32.shared-gcc
          - mxe-i686-w64-mingw32.shared-sdl2
          - mxe-i686-w64-mingw32.shared-freeglut
          - mxe-i686-w64-mingw32.shared-freetype
          - mxe-i686-w64-mingw32.shared-libpng
          - mxe-i686-w64-mingw32.shared-zlib
          - mxe-i686-w64-mingw32.shared-opencv
          - mxe-i686-w64-mingw32.shared-pkgconf
          - nasm
      script:
        # XXX: disable LTO for now to avoid subprojects linking failure
        - meson -Db_lto=false --cross-file cross/mxe-i686-w64-mingw32-cross.txt builddir
        - meson configure builddir
        - ninja -C builddir

    - env:
      - MXE_CPU=x86_64
      - PATH="/usr/lib/mxe/usr/bin/:$PATH"
      addons:
        apt:
          sources:
          - sourceline: 'deb http://pkg.mxe.cc/repos/apt/debian jessie main'
            key_url: 'http://pkg.mxe.cc/repos/apt/conf/mxeapt.gpg'
          packages:
          - mxe-x86-64-w64-mingw32.shared-gcc
          - mxe-x86-64-w64-mingw32.shared-sdl2
          - mxe-x86-64-w64-mingw32.shared-freeglut
          - mxe-x86-64-w64-mingw32.shared-freetype
          - mxe-x86-64-w64-mingw32.shared-libpng
          - mxe-x86-64-w64-mingw32.shared-zlib
          - mxe-x86-64-w64-mingw32.shared-opencv
          - mxe-x86-64-w64-mingw32.shared-pkgconf
          - nasm
      script:
        # XXX: disable LTO for now to avoid subprojects linking failure
        - meson -Db_lto=false --cross-file cross/mxe-x86-64-w64-mingw32-cross.txt builddir
        - meson configure builddir
        - ninja -C builddir
