version: 1.0.{build}

before_build:
  - git clone --depth 1 https://github.com/mupen64plus/mupen64plus-win32-deps.git ..\mupen64plus-win32-deps

build_script:
  - msbuild projects\msvc\mupen64plus-core.vcxproj /p:Configuration=Release;Platform=x64
  - msbuild projects\msvc\mupen64plus-core.vcxproj /p:Configuration=Release;Platform=Win32
  - msbuild projects\msvc\mupen64plus-core.vcxproj /p:Configuration=New_Dynarec_Release;Platform=x64
  - msbuild projects\msvc\mupen64plus-core.vcxproj /p:Configuration=New_Dynarec_Release;Platform=Win32

after_build:
  - ps: $env:rev = git describe --tags
  - 7z a -t7z "build\mupen64plus-core_v%rev%_x64-Release.7z" ".\projects\msvc\x64\Release\*.dll"
  - 7z a -t7z "build\mupen64plus-core_v%rev%_x86-Release.7z" ".\projects\msvc\Win32\Release\*.dll"
  - 7z a -t7z "build\mupen64plus-core_v%rev%_x64-NewDynarec.7z" ".\projects\msvc\x64\New_Dynarec_Release\*.dll"
  - 7z a -t7z "build\mupen64plus-core_v%rev%_x86-NewDynarec.7z" ".\projects\msvc\Win32\New_Dynarec_Release\*.dll"

artifacts:
  - path: build\*.7z
    name: Core
