@echo off
setlocal enableextensions

:: 	Generic test to detect tainted build environment
find /? >nul 2>&1
if errorlevel 1 (
	echo WARNING: GNU Core Utilities in PATH can break MSVC
	echo.
)

:: 	Splitting the arguments of this script from those of the MSVC compiler:
::
::	* Arguments with conflicting syntax can terminate the script abruptly
::	* The variable 'GAS_EXTRA' isn't used in some cases
::
set GAS_SRCDIR=
set GAS_OBJDIR=
set GAS_EXTRA=
for /f "tokens=1,2*" %%A in ('echo %*') do (
	set GAS_SRCDIR=%%A
	set GAS_OBJDIR=%%B
	set GAS_EXTRA=%%C
)
set GAS_CLARG=%GAS_OBJDIR%
if defined GAS_EXTRA set GAS_CLARG=%GAS_OBJDIR% %GAS_EXTRA%

:: 	"Anti-PEBCAK":
::
::	* Ensure that 'GAS_SRCDIR' and 'GAS_OBJDIR' exist or are defined and
::	 send an error signal if not
::
if not exist "%GAS_SRCDIR%asm_defines.c" exit 202
if not defined GAS_OBJDIR exit 303

:: 	Legacy code adaptation for this script:
::
::	* Delete the libraries previously generated by 'gawk' or this script
::	* MSVC compiler, if all goes well it will generate 'asm_defines.obj'
::
del /f /q "%GAS_SRCDIR%asm_defines_*.h" 2>nul
cl /c /Fo%GAS_CLARG% /I ..\..\src "%GAS_SRCDIR%asm_defines.c"

:: 	If 'asm_defines.obj' does not exist, send error
if not exist "%GAS_OBJDIR%asm_defines.obj" exit 404

:: 	Adaptation of 'gen_asm_defines.awk' / 'gen_asm_script.sh':
::
::	1. Display 'asm_defines.obj' as a list, looking for patterns
::	  '@ASM_DEFINE offsetof_struct_'
::	2. Sort for easy reading, the result is interpreted as an array
::	  with ' ' as default delimiter in the 'for' command
::	3. The for's 'tokens=2,3' ignores pattern "1" (@ASM_DEFINE) and anything
::	  beyond "3", take "2" (offsetof*) as 'J' and "3" (hex value) as 'K'
::	4. Print current values and repeat steps 3 and 4 on the next line
::	  until EOF is reached
::
for /f "tokens=2,3" %%J in ('type "%GAS_OBJDIR%asm_defines.obj" ^| findstr /C:"@ASM_DEFINE offsetof_struct_" ^| sort') do (
	echo %%define %%J ^(%%K^)>> "%GAS_SRCDIR%asm_defines_nasm.h"
	echo #define %%J ^(%%K^)>> "%GAS_SRCDIR%asm_defines_gas.h"
)

:: 	Display 'asm_defines_nasm.h' in the MSVC log
echo.
type "%GAS_SRCDIR%asm_defines_nasm.h"
echo.
exit 0
